# build image from Docker Hub (see https://registry.hub.docker.com/repos/shippableimages/)
# build_image: shippableimages/ubuntu1404_python
language: python
python:
  - "2.7"
services:
  - neo4j
cache: true
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
    - pip install -r requirements.txt
before_script:
    - export PYTHONPATH=$PYTHONPATH:$(pwd)
    - mkdir -p shippable/testresults
    - mkdir -p shippable/codecoverage
# command to run tests, e.g. python setup.py test
script:
    - python --version
    - python misc/py2neo_2.0_samples/seed_database.py test
    - behave -f progress --junit --tags=~@xfail features/
