language: python
python:
  - "2.7"
services:
  - neo4j
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: "pip install -r requirements.txt"
# command to run tests, e.g. python setup.py test
script:  "python agora/py2neo_2.0_tests/seed_database.py test"