language:
    python

python:
  - "2.7"

services:
  - neo4j

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
    - pip install -r requirements.txt

env:
    - NEO4J_VERSION="2.1.7"

before_install:
    - wget dist.neo4j.org/neo4j-community-$NEO4J_VERSION-unix.tar.gz
    - tar -xzf neo4j-community-$NEO4J_VERSION-unix.tar.gz
    - neo4j-community-$NEO4J_VERSION/bin/neo4j start

before_script:
    - export PYTHONPATH=$PYTHONPATH:$(pwd)

# command to run tests, e.g. python setup.py test
script:
    - python agora_tests/py2neo_2.0/seed_database.py test